/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

public class App {


    public static void main(String[] args) {
        // LinkedList<Integer> linkedlist = new LinkedList<Integer>();
        // linkedlist.insert(5);
        // linkedlist.insert(8);
        // linkedlist.insert(9);
        // System.out.println(linkedlist);
        // linkedlist.addBefore(10,5);
        // linkedlist.addBefore(3,10);
        // linkedlist.addAfter(3,10);
        // linkedlist.addAfter(3,3);


        // System.out.println(linkedlist.include(9));
        // System.out.println(linkedlist);

        
        
    }
}
